Exercise 1: Computing most recently seen list
lincoln
abraham
earth
the
from
perish
not
shall
people
for
by
of
government
that
and

freedom
birth
new
a
have
god
under
nation
this
vain
in
died
dead
these
resolve
highly
here
we
devotion
measure
full
last
gave
they
which
cause
to
increased
take
honored
us
before
remaining
task
great
dedicated
be
rather
is
it
advanced
nobly
so
far
thus
fought
who
work
unfinished
living
did
what
forget
never
can
but
say
remember
long
nor
note
little
will
world
detract
or
add
power
poor
our
above
consecrated
struggled
men
brave
ground
hallow
consecrate
dedicate
sense
larger
do
should
proper
fitting
altogether
live
might
lives
their
those
place
resting
final
as
field
portion
come
war
battlefield
on
met
are
endure
conceived
any
whether
testing
civil
engaged
now
equal
created
all
proposition
liberty
continent
forth
brought
fathers
ago
years
seven
score
four

Exercise 2: Computing punctuation set
, - . 

Exercise 3: Computing word frequencies
: 7
a: 7
above: 1
abraham: 1
add: 1
advanced: 1
ago: 1
all: 1
altogether: 1
and: 6
any: 1
are: 3
as: 1
battlefield: 1
be: 2
before: 1
birth: 1
brave: 1
brought: 1
but: 2
by: 1
can: 5
cause: 1
civil: 1
come: 1
conceived: 2
consecrate: 1
consecrated: 1
continent: 1
created: 1
dead: 3
dedicate: 2
dedicated: 4
detract: 1
devotion: 2
did: 1
died: 1
do: 1
earth: 1
endure: 1
engaged: 1
equal: 1
far: 2
fathers: 1
field: 1
final: 1
fitting: 1
for: 5
forget: 1
forth: 1
fought: 1
four: 1
freedom: 1
from: 2
full: 1
gave: 2
god: 1
government: 1
great: 3
ground: 1
hallow: 1
have: 5
here: 8
highly: 1
honored: 1
in: 4
increased: 1
is: 3
it: 5
larger: 1
last: 1
liberty: 1
lincoln: 1
little: 1
live: 1
lives: 1
living: 2
long: 2
measure: 1
men: 2
met: 1
might: 1
nation: 5
never: 1
new: 2
nobly: 1
nor: 1
not: 5
note: 1
now: 1
of: 5
on: 2
or: 2
our: 2
people: 3
perish: 1
place: 1
poor: 1
portion: 1
power: 1
proper: 1
proposition: 1
rather: 2
remaining: 1
remember: 1
resolve: 1
resting: 1
say: 1
score: 1
sense: 1
seven: 1
shall: 3
should: 1
so: 3
struggled: 1
take: 1
task: 1
testing: 1
that: 13
the: 11
their: 1
these: 2
they: 3
this: 4
those: 1
thus: 1
to: 8
under: 1
unfinished: 1
us: 3
vain: 1
war: 2
we: 10
what: 2
whether: 1
which: 2
who: 3
will: 1
work: 1
world: 1
years: 1
