Exercise 1: Computing most recently seen list
roosevelt
delano
franklin
president
empire
japanese
the
and
states
united
between
existed
has
war
of
state
a
1941
7
december
sunday
on
japan
by
attack
dastardly
unprovoked
since
that
declare
congress
ask
i
god
us
help
so
triumph
inevitable
gain
will
we
people
our
determination
unbounding
with
forces
armed
in
confidence
danger
grave
are
interests
territory
fact
at
blinking
no
is
there
exist
hostilities
endanger
again
never
shall
treachery
form
this
certain
very
it
make
but
uttermost
to
ourselves
defend
only
not
assert
when
interpret
believe
victory
absolute
through
win
might
righteous
their
american
invasion
premeditated
overcome
take
may
long
how
matter
against
onslaught
character
remember
nation
whole
always
defense
for
taken
be
measures
all
directed
have
navy
army
commanderinchief
as
safety
life
implications
understand
well
opinions
formed
already
themselves
speak
today
yesterday
facts
area
pacific
throughout
extending
offensive
surprise
undertaken
therefore
island
midway
attacked
morning
wake
night
last
islands
philippine
guam
kong
hong
malaya
an
launched
also
government
honolulu
francisco
san
seas
high
torpedoed
reported
been
ships
addition
lost
lives
many
you
tell
regret
military
naval
damage
severe
caused
hawaiian
peace
continued
hope
expressions
statements
false
deceive
sought
deliberately
time
intervening
during
ago
weeks
even
or
days
planned
was
obvious
makes
from
hawaii
distance
recorded
hint
threat
contained
negotiations
diplomatic
existing
continue
useless
seemed
stated
reply
while
message
recent
formal
secretary
delivered
colleague
his
ambassador
oahu
bombing
commenced
had
squadrons
air
after
hour
one
indeed
maintenance
toward
looking
emperor
its
conversation
still
solicitation
suddenly
america

infamy
live
which
date

Exercise 2: Computing punctuation set
, - . 

Exercise 3: Computing word frequencies
: 2
1941: 2
7: 2
a: 5
absolute: 1
addition: 1
after: 1
again: 1
against: 2
ago: 1
air: 2
all: 1
already: 1
also: 1
always: 1
ambassador: 1
america: 1
american: 6
an: 1
and: 18
are: 1
area: 1
armed: 2
army: 1
as: 1
ask: 1
assert: 1
at: 3
attack: 5
attacked: 6
be: 2
been: 2
believe: 1
between: 2
blinking: 1
bombing: 1
but: 1
by: 3
caused: 1
certain: 1
character: 1
colleague: 1
commanderinchief: 1
commenced: 1
confidence: 1
congress: 2
contained: 1
continue: 1
continued: 1
conversation: 1
damage: 1
danger: 1
dastardly: 1
date: 1
days: 1
deceive: 1
december: 2
declare: 1
defend: 1
defense: 1
delano: 1
deliberately: 3
delivered: 1
determination: 1
diplomatic: 1
directed: 1
distance: 1
during: 1
emperor: 1
empire: 2
endanger: 1
even: 1
exist: 1
existed: 1
existing: 1
expressions: 1
extending: 1
fact: 1
facts: 1
false: 1
for: 3
forces: 6
form: 1
formal: 1
formed: 1
francisco: 1
franklin: 1
from: 1
gain: 1
god: 1
government: 3
grave: 1
guam: 1
had: 1
has: 4
have: 4
hawaii: 1
hawaiian: 1
help: 1
high: 1
hint: 1
his: 1
hong: 1
honolulu: 1
hope: 1
hostilities: 1
hour: 1
how: 1
i: 6
implications: 1
in: 8
indeed: 1
inevitable: 1
infamy: 1
interests: 1
interpret: 1
intervening: 1
invasion: 1
is: 1
island: 3
islands: 2
it: 6
its: 2
japan: 5
japanese: 10
kong: 1
last: 4
launched: 1
life: 1
live: 1
lives: 1
long: 1
looking: 1
lost: 1
maintenance: 1
make: 1
makes: 1
malaya: 1
many: 2
matter: 1
may: 1
measures: 1
message: 1
midway: 1
might: 1
military: 1
morning: 1
nation: 3
naval: 2
navy: 1
negotiations: 1
never: 1
night: 4
no: 3
not: 1
oahu: 1
obvious: 1
of: 21
offensive: 1
on: 3
one: 1
only: 1
onslaught: 1
opinions: 1
or: 3
our: 9
ourselves: 1
overcome: 1
pacific: 2
peace: 3
people: 5
philippine: 1
planned: 1
premeditated: 1
president: 1
recent: 1
recorded: 1
regret: 1
remember: 1
reply: 2
reported: 1
righteous: 1
roosevelt: 1
safety: 1
san: 1
seas: 1
secretary: 1
seemed: 1
severe: 1
shall: 1
ships: 1
since: 1
so: 1
solicitation: 1
sought: 1
speak: 1
squadrons: 1
state: 2
stated: 1
statements: 1
states: 6
still: 1
suddenly: 1
sunday: 1
surprise: 1
take: 1
taken: 1
tell: 1
territory: 1
that: 13
the: 43
their: 2
themselves: 1
there: 1
therefore: 1
this: 4
threat: 1
through: 1
throughout: 1
time: 1
to: 11
today: 1
torpedoed: 1
toward: 1
treachery: 1
triumph: 1
unbounding: 1
understand: 1
undertaken: 1
united: 6
unprovoked: 1
us: 4
useless: 1
uttermost: 1
very: 3
victory: 1
wake: 1
war: 2
was: 4
we: 2
weeks: 1
well: 1
when: 1
which: 1
while: 1
whole: 1
will: 8
win: 1
with: 4
yesterday: 4
you: 1
