Exercise 1: Computing most recently seen list
zimmermann
signed
peace
make
to
months
few
a
in
england
compelling
of
prospect
the
offers
now
submarines
our
employment
ruthless
that
fact
attention
presidents
call
please
ourselves
and
japan
between
mediate
time
same
at
adherence
immediate
invite
initiative
own
his
on
should
he
suggestion
add
certain
is
america
states
united
with
war
outbreak
as
soon
secretly
most
above
president
inform
will
you
left
detail
settlement
arizona
mexico
new
texas
territory
lost
reconquer
part
understanding
an
support
financial
generous
together
basis
following
alliance
proposal
we
succeeding
not
this
event
neutral
keep
spite
endeavor
shall
warfare
submarine
unrestricted
february
first
begin
intend

Exercise 2: Computing punctuation set
' , . : 

Exercise 3: Computing word frequencies
a: 2
above: 1
add: 1
adherence: 1
alliance: 1
america: 2
an: 1
and: 5
arizona: 1
as: 2
at: 1
attention: 1
basis: 1
begin: 1
between: 1
call: 1
certain: 1
compelling: 1
detail: 1
employment: 1
endeavor: 1
england: 1
event: 1
fact: 1
february: 1
few: 1
financial: 1
first: 1
following: 1
generous: 1
he: 1
his: 1
immediate: 1
in: 5
inform: 1
initiative: 1
intend: 1
invite: 1
is: 3
japan: 2
keep: 1
left: 1
lost: 1
make: 4
mediate: 1
mexico: 3
months: 1
most: 1
neutral: 1
new: 1
not: 1
now: 1
of: 10
offers: 1
on: 4
our: 2
ourselves: 1
outbreak: 1
own: 1
part: 1
peace: 2
please: 1
president: 1
presidents: 1
proposal: 1
prospect: 1
reconquer: 1
ruthless: 1
same: 1
secretly: 1
settlement: 1
shall: 1
should: 1
signed: 1
soon: 1
spite: 1
states: 2
submarine: 1
submarines: 1
succeeding: 1
suggestion: 1
support: 1
territory: 1
texas: 1
that: 3
the: 16
this: 2
time: 1
to: 7
together: 2
understanding: 1
united: 2
unrestricted: 1
war: 2
warfare: 1
we: 3
will: 1
with: 1
you: 2
zimmermann: 1
